version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo Build started on `date`
      - export CODEBUILD_GIT_BRANCH=${CODEBUILD_WEBHOOK_BASE_REF##*/}
      - echo $CODEBUILD_GIT_BRANCH
      - pip3 install -r ./requirements.txt
      - flake8 .
      - pytest -sv tests
      - echo $CODEBUILD_WEBHOOK_EVENT;
      - |
        if [ $CODEBUILD_WEBHOOK_EVENT = "PULL_REQUEST_MERGED" ]; then
          npm install -g serverless
          npm install
          if [ $CODEBUILD_GIT_BRANCH = "master" ]; then
              serverless deploy --env stage2
          elif [ $CODEBUILD_GIT_BRANCH = "production" ]; then
              serverless deploy --env prod
          fi;
        else
          echo 'taras'
        fi;
